### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by Samliuyincheng** [dean0x7d/pybinding#24]
Hi, I am relatively new to python so please forgive me.

I tried to install the pybinding under python 3.5 and when I run the 
`import pybinding as pb`

it gives me 

> Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\OneDrive\桌面\Project_IMRE\Python\MOS2 QD Simulation\MOS2 QD Simulation\MOS2_QD_Simulation.py", line 3, in <module>
    import pybinding as pb
  File "C:\Users\User\AppData\Local\Programs\Python\Python35\lib\site-packages\pybinding\__init__.py", line 20, in <module>
    import _pybinding as _cpp
ImportError: DLL load failed: The specified procedure could not be found.
The thread 'MainThread' (0x1) has exited with code 0 (0x0).
The program 'python.exe' has exited with code 0 (0x0).

> 
I wonder how to deal with the issue

**Comment by dean0x7d** [comment]
The newly released v0.9.5 fixes a few installation issues. Please give it a try. (You will just need to update to Python 3.6+ since support for Python 3.5 has been dropped.)
